export const clubs_gym = [
  { id: "6623005224", state: "Queretaro",   name: "Cimatario",              },
  { id: "fa3dde34d7", state: "Monterrey",   name: "El Molino",              },
  { id: "236a7d40af", state: "Guadalajara", name: "Punto Rio Nilo",         },
  { id: "90e4b5c13a", state: "San Luis",    name: "The Park",               },
  { id: "6f1c8b2375", state: "Leon",        name: "Punto León",             },
  { id: "c022aa7cdc", state: "Queretaro",   name: "Candiles",               },
  { id: "2e7d9a4c05", state: "San Luis",    name: "Glorieta",               },
  { id: "8c1029a5e7", state: "Queretaro",   name: "Antea",                  },
  { id: "f1e2d3c4b5", state: "Guadalajara", name: "Plaza Del Angel",        },
  { id: "358829c03d", state: "Leon",        name: "Lindavista",             },
  { id: "17cf8bbf29", state: "Monterrey",   name: "Santa Catarina",         },
  { id: "660e5a1d8c", state: "Monterrey",   name: "La Estanzuela",          },
  { id: "c6232e9461", state: "Monterrey",   name: "Arcadia",                },
  { id: "0b0986e177", state: "Saltillo",    name: "Santa Isabel",           },
  { id: "c4e220d3af", state: "Puebla",      name: "Torrecillas",            }, 
  { id: "aa85485a04", state: "Cuernavaca",  name: "Galerías Cuernavaca",    }, 
  { id: "6a2052d8f9", state: "CDMX",        name: "Paseo Acoxpa",           }, 
  { id: "9e4f35b27c", state: "Edo de Mex",  name: "Satelite",               }, 
  { id: "8932ff1b6e", state: "Edo de Mex",  name: "San Marcos",             }, 
  { id: "d7b69c1f80", state: "Puebla",      name: "La Paz Puebla",          }, 
  { id: "54b5f8a3c2", state: "Edo de Mex",  name: "Valle Dorado",           }, 
  { id: "bf41e2d6ab", state: "CDMX",        name: "Tlatelolco",             }, 
  { id: "eac1e502d3", state: "CDMX",        name: "Encuentro Oceania",      }, 
  { id: "44a6932e11", state: "Puebla",      name: "Serviplaza Villa Verde", }, 
  { id: "b291e7d7f0", state: "Edo de Mex",  name: "Tollocan",               }, 
  { id: "5dc0a1b409", state: "Puebla",      name: "Angelópolis",            }, 
  { id: "7aa8f6d5c3", state: "Edo de Mex",  name: "Coacalco",               }, 
  { id: "15bd2f6108", state: "CDMX",        name: "Acueducto",              }, 
  { id: "b70f4e2d6a", state: "VER",         name: "Jardines Xalapa",        }, 
  { id: "257d3e6a8b", state: "Veracruz",    name: "Center Plazas",          }, 
  { id: "a49d5f73c4", state: "CDMX",        name: "Mixcoac",                }, 
  { id: "31b8e2a04f", state: "CDMX",        name: "Cumbres 1188",           }, 
  { id: "3d207a9c12", state: "Edo de Mex",  name: "Centro Las Americas",    }, 
  { id: "9b4a5e7d13", state: "Veracruz",    name: "Andamar",                }, 
  { id: "c50f0f52f8", state: "Veracruz",    name: "Los Pinos",              }, 
  { id: "4bfa66b080", state: "Mazatlan",    name: "Gran Plaza Mazatlan",    }, 
  { id: "8173b8366a", state: "CDMX",        name: "Altolivo",               }, 
  { id: "3d90a85839", state: "Guadalajara", name: "Celta Guadalajara",      }, 
  { id: "1e3a0ef22e", state: "Mérida",      name: "Harbor Mérida",          }, 
  { id: "c45c1a9f19", state: "Guadalajara", name: "Estadio Gdl",            }, 
  { id: "7fc28ff6a1", state: "Culiacán",    name: "Zapata Culiacan",        }, 
  { id: "d37333456f", state: "Cancún",      name: "Malecón Las Américas",   }, 
  { id: "61b395fb2b", state: "León",        name: "Parque Vértice",         }, 
  { id: "49fa0060c3", state: "Guadalajara", name: "Galerias Guadalajara",   }, 
  { id: "5fdc64fa8d", state: "Guadalajara", name: "Punto Sur",              }, 
  { id: "98f1370821", state: "EEUU",        name: "USA",                    },  
  { id: "61480e707c", state: "CDMX",        name: "Gran Sur",               },  
  { id: "66dab86bf2", state: "Acapulco",    name: "Multiplaza las Palmas",  },  
  { id: "216428d3f9", state: "Edo de Mex",  name: "Cuatro Caminos",         },  
  { id: "d6830a6ee4", state: "Mérida",      name: "Canek",                  },  
]